from __future__ import annotations

COMMON_FIELDS = [
    "id",
    "created_at",
    "updated_at",
    "source",
    "confidence",
    "status",
    "llm_notes",
]

SCHEMAS = {
    "user_profile": COMMON_FIELDS + ["name", "age", "sex", "height_cm", "country", "timezone"],
    "goals": COMMON_FIELDS + ["goal_type", "goal_description", "target_value", "target_unit", "target_date", "priority"],
    "targets": COMMON_FIELDS
    + [
        "effective_from",
        "effective_to",
        "target_type",
        "calories_kcal",
        "protein_g",
        "carbs_g",
        "fat_g",
        "fiber_g",
        "water_l",
        "steps",
        "training_days_per_week",
        "calculation_method",
    ],
    "body_stats": COMMON_FIELDS
    + ["date", "weight_kg", "waist_cm", "body_fat_percent", "resting_hr", "sleep_hours", "steps", "measurement_notes"],
    "diet_history": COMMON_FIELDS
    + [
        "date",
        "calories_kcal",
        "protein_g",
        "carbs_g",
        "fat_g",
        "fiber_g",
        "salt_g",
        "water_l",
        "alcohol_units",
        "adherence_score",
        "summary",
    ],
    "training_history": COMMON_FIELDS
    + [
        "date",
        "trained",
        "session_name",
        "training_type",
        "duration_min",
        "volume_summary",
        "intensity_summary",
        "steps",
        "cardio_min",
        "pain_notes",
        "performance_notes",
    ],
    "diet_plan": COMMON_FIELDS
    + ["date", "calories_kcal", "protein_g", "carbs_g", "fat_g", "fiber_g", "water_l", "plan_summary", "compensation_reason"],
    "training_plan": COMMON_FIELDS
    + [
        "date",
        "planned_training",
        "session_name",
        "training_type",
        "duration_min",
        "intensity_target",
        "progression_rule",
        "plan_summary",
        "compensation_reason",
    ],
    "ingredients": COMMON_FIELDS
    + [
        "name",
        "brand",
        "barcode",
        "basis_type",
        "basis_quantity",
        "basis_unit",
        "calories_kcal",
        "protein_g",
        "carbs_g",
        "fat_g",
        "fiber_g",
        "salt_g",
        "source_url",
        "last_verified",
    ],
    "recipes": COMMON_FIELDS
    + [
        "name",
        "servings",
        "serving_description",
        "total_calories_kcal",
        "total_protein_g",
        "total_carbs_g",
        "total_fat_g",
        "total_fiber_g",
        "total_salt_g",
        "per_serving_calories_kcal",
        "per_serving_protein_g",
        "per_serving_carbs_g",
        "per_serving_fat_g",
        "per_serving_fiber_g",
        "per_serving_salt_g",
        "last_verified",
    ],
    "recipe_ingredients": COMMON_FIELDS
    + [
        "recipe_id",
        "ingredient_id",
        "ingredient_name",
        "brand",
        "quantity",
        "unit",
        "basis_type",
        "basis_quantity",
        "basis_unit",
        "calories_kcal",
        "protein_g",
        "carbs_g",
        "fat_g",
        "fiber_g",
        "salt_g",
        "preparation_notes",
    ],
    "dietary_restrictions": COMMON_FIELDS + ["restriction_type", "name", "severity", "impact", "checked_on"],
    "health_notes": COMMON_FIELDS + ["date", "note_type", "description", "impact_on_diet", "impact_on_training"],
    "deviations": COMMON_FIELDS
    + ["date", "deviation_type", "description", "estimated_calories_delta", "estimated_protein_delta", "estimated_training_impact", "adjustment_needed"],
    "fridge_items": COMMON_FIELDS + ["item_name", "ingredient_id", "quantity", "unit", "expires_on", "location"],
    "shopping_list": COMMON_FIELDS + ["item_name", "ingredient_id", "quantity", "unit", "reason", "needed_by", "purchased"],
    "web_research": COMMON_FIELDS + ["date", "topic", "source_name", "source_url", "summary"],
}

TABLE_FILES = {table: f"{table}.csv" for table in SCHEMAS}

DAILY_DATE_FIELDS = {
    "body_stats": "date",
    "diet_history": "date",
    "training_history": "date",
    "diet_plan": "date",
    "training_plan": "date",
    "deviations": "date",
    "health_notes": "date",
    "web_research": "date",
}

DATE_FIELDS = {"date", "target_date", "effective_from", "effective_to", "last_verified", "checked_on", "expires_on", "needed_by"}
TIMESTAMP_FIELDS = {"created_at", "updated_at"}

ENUM_FIELDS = {
    "source": {"user", "agent", "calculation", "label", "web", "estimate", "import"},
    "confidence": {"exact", "high", "medium", "low", "estimate", "unknown"},
    "status": {"active", "inactive", "draft", "incomplete", "archived"},
    "sex": {"male", "female"},
    "goal_type": {"fat_loss", "muscle_gain", "recomposition", "maintenance", "strength", "endurance", "health", "habit", "other"},
    "target_type": {"diet", "training", "combined"},
    "training_type": {"strength", "hypertrophy", "cardio", "mobility", "sport", "rest", "mixed", "other"},
    "basis_type": {"per_100g", "per_unit", "per_package"},
    "restriction_type": {"allergy", "intolerance", "medical", "preference", "religious", "ethical", "other"},
    "trained": {"yes", "no", "true", "false", "1", "0"},
    "planned_training": {"yes", "no", "true", "false", "1", "0"},
    "purchased": {"yes", "no", "true", "false", "1", "0"},
}

NUMERIC_FIELDS = {
    "age",
    "height_cm",
    "target_value",
    "priority",
    "weight_kg",
    "waist_cm",
    "body_fat_percent",
    "resting_hr",
    "sleep_hours",
    "steps",
    "calories_kcal",
    "protein_g",
    "carbs_g",
    "fat_g",
    "fiber_g",
    "water_l",
    "training_days_per_week",
    "salt_g",
    "alcohol_units",
    "adherence_score",
    "duration_min",
    "cardio_min",
    "basis_quantity",
    "servings",
    "quantity",
    "estimated_calories_delta",
    "estimated_protein_delta",
    "total_calories_kcal",
    "total_protein_g",
    "total_carbs_g",
    "total_fat_g",
    "total_fiber_g",
    "total_salt_g",
    "per_serving_calories_kcal",
    "per_serving_protein_g",
    "per_serving_carbs_g",
    "per_serving_fat_g",
    "per_serving_fiber_g",
    "per_serving_salt_g",
}
NON_NEGATIVE_NUMERIC_FIELDS = NUMERIC_FIELDS - {"estimated_calories_delta", "estimated_protein_delta"}
POSITIVE_NUMERIC_FIELDS = {"servings", "basis_quantity", "height_cm", "weight_kg", "quantity"}

REQUIRED_FIELDS = {
    "user_profile": {"name", "age", "sex", "height_cm"},
    "goals": {"goal_type", "goal_description"},
    "targets": {"effective_from", "target_type"},
    "body_stats": {"date", "weight_kg", "waist_cm", "body_fat_percent"},
    "diet_history": {"date", "calories_kcal", "protein_g"},
    "training_history": {"date", "trained", "training_type"},
    "diet_plan": {"date", "calories_kcal", "protein_g", "carbs_g", "fat_g"},
    "training_plan": {"date", "planned_training", "training_type"},
    "ingredients": {"name", "basis_type"},
    "recipes": {"name", "servings"},
    "recipe_ingredients": {"recipe_id", "ingredient_name", "quantity", "unit", "basis_type", "basis_quantity", "basis_unit"},
    "dietary_restrictions": {"restriction_type", "name", "checked_on"},
    "health_notes": {"date", "note_type", "description"},
    "deviations": {"date", "deviation_type", "description"},
    "fridge_items": {"item_name", "quantity", "unit"},
    "shopping_list": {"item_name", "quantity", "unit"},
    "web_research": {"date", "topic", "source_name", "source_url"},
}
